### ISSUE TITLE
提议: nickname 的问题

### ISSUE THREAD

**Issue by gonglexin** [phoenix-china/phoenix_china#6]
nickname 可以修改的情况下，会造成一些问题，比如
- A 先将 nickname 修改为 B 的，B 再修改为 A 的，那么很多地方看上去像两个人互换了。 
- A 将 nickname 修改为其他，A 在系统中发给其他用户的 @ 消息，其他用户在消息模块只能看到老的 nickname, 无法找到真正的 A 用户。

可以考虑以下两种：

1. 增加一个 username 做用户的唯一 identifier 标识。只允许字母数字和下划线。现有用户直接取满足条件的 nickname 做 username, nickname 为中文则取邮箱名。username  不允许修改，nickname 随意改。现有系统 用户连接方式均修改为 username 的形式。
2. nickname 不允许修改，相当于用户唯一 identifier 。

**Comment by nanlong** [comment]
附议，近期解决
